---
- name: build vms
  hosts: localhost
  become: false
  vars_files:
    - "{{ top_dir }}/proxmox-root.yml"
  roles:
    - role: manage-proxmox
      vars:
        node: proxmox
        pve_domain: proxmox.host.local
        pve_kvm_template:
          - clone: template
            vmid: 9000
            newid: 9010
            name: molecule
            cores: 2
            memory: 4096
            storage: local
            format: qcow2
            mac: 'XX:XX:XX:XX:XX:XX'
