---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.general
  vars:
    - node: proxmox
    - molecule_instance_config: "{{ top_dir }}/testing/instance_config.yml"
  vars_files:
    - "{{ lookup('env', 'PWD') }}/molecule/default/molecule.yml"
    - "{{ top_dir }}/proxmox-root.yml"
  tasks:

    # Remove instances by numeric vmid instead of by name, which seems
    # safer and more reliable. Since the Ansible lookup() plugin complains
    # even when error=ingore is set, just create an empty file to ignore
    # a missing instance_configs.
    - name: "Check for instance configs."
      stat:
        path: "{{ molecule_instance_config }}"
      register: instance_config_stat

    - name: "Remove molecule instance(s)."
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        state: absent
        vmid: "{{ i.vmid }}"
        force: yes
        timeout: 500
      loop: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
      loop_control:
        loop_var: i
        label: "{{ i.instance, i.vmid }}"
      when: not instance_config_stat.stat.exists

    - name: Write Molecule instance configs
      copy:
        dest: "{{ molecule_instance_config }}"
        content: "{{ {} | to_yaml }}"
