- name: build vms
  hosts: localhost
  become: false
  vars_files:
    - "{{ top_dir }}/proxmox-root.yml"
  vars:
    node: proxmox
  tasks:
    - name: is the test vm running
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        vmid: "9010"
        name: "molecule-test"
        state: current
      register: vms

    - name: Stop test KVM vm
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        vmid: "9010"
        name: "molecule-test"
        state: stopped
        force: yes
        timeout: 500
      when: vms.status.find("running") != -1

    - name: Pause for 10 seconds for shutdown
      ansible.builtin.pause:
        seconds: 10

    - name: Remove test KVM vm
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        vmid: "9010"
        name: "molecule-test"
        state: absent
        force: yes
        timeout: 500
