-   id: ansible-lint
    name: ansible-lint
    description: This hook runs ansible-lint
    entry: testing/lint.sh
    language: script
    pass_filenames: false
    always_run: true
    verbose: true
-   id: molecule-test
    name: molecule-test
    description: This hook runs molecule test
    entry: testing/molecule.sh
    language: script
    pass_filenames: false
    always_run: true
