#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the
# UPS goes back on to the mains after a power failure.
# We send an email message to root to notify him.
#
SYSADMIN=logs@horwood.biz
APCUPSD_MAIL="/usr/bin/mail"

HOSTNAME=`hostname`
MSG="$HOSTNAME Power has returned"
#
(
   echo "Captain, main power has been restored!"
   echo " "
   /sbin/apcaccess status| grep "LOADPCT"
   /sbin/apcaccess status| grep "BCHARGE"
   /sbin/apcaccess status| grep "TIMELEFT"
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN

exit 0
